# Generated by Django 3.2.4 on 2021-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.CharField(default=0, max_length=10000),
        ),
    ]
